import * as d3 from "d3";
import { feature } from "topojson-client";
import "./styles.css";
const BASE=import.meta.env.BASE_URL,dataUrl=p=>`${BASE}${String(p).replace(/^\//,"")}`;
const SKILLS={all:"All skill levels",low:"Low-skilled",medium:"Medium-skilled",high:"High-skilled"};
document.querySelector("#app").innerHTML=`<div class="shell">
<header class="mast"><div><div class="kicker">LABOUR AND UNEQUAL EXCHANGE</div><h1>Unequal Exchange Atlas</h1><p class="lede">Explore where the labour embodied in consumption is performed, how those flows move between countries and regions, and how large they are relative to population, domestic labour and GDP.</p></div><div class="badge">EXIOBASE 3.8.2</div></header>
<section class="toolbar"><div><span class="control-label">View</span><div class="segmented" id="viewButtons"><button class="active" data-view="labour_hours">Labour hours</button><button data-view="wage_value">Wage value</button></div></div><label><span>Map measure</span><select id="metric" class="control"></select></label><label><span>Skill level</span><select id="skill" class="control"><option value="all">All skill levels</option><option value="low">Low-skilled</option><option value="medium">Medium-skilled</option><option value="high">High-skilled</option></select></label><label><span>Year</span><select id="year" class="control"></select></label><div class="toolbar-actions"><button id="summaryBtn" class="control">North–South dashboard</button><button id="methodologyBtn" class="control">Methodology</button></div></section>
<section class="timeline card"><button id="playBtn" class="play">▶</button><div class="timeline-main"><div class="timeline-labels"><strong id="timelineYear">—</strong><span id="timelineRange"></span></div><input id="yearSlider" type="range" min="0" max="0" value="0" step="1"></div></section>
<div class="coverage-note"><strong>Geographic coverage:</strong> EXIOBASE reports 44 countries separately and groups the rest of the world into five regions. Countries inside those groups share the value of their EXIOBASE region.</div>
<main class="grid"><section class="card mapwrap"><div id="loading" class="loading">Loading EXIOBASE-derived results…</div><svg id="map" viewBox="0 0 1000 560"></svg><div class="legend"><div class="small muted">net supplied ← → net appropriated</div><div class="legendbar"></div><div id="legendScale" class="small"></div></div></section><aside id="details" class="card side"><div class="muted">Select a country or aggregate region.</div></aside></main>
<section id="summaryPanel" class="card section dashboard" hidden><div class="section-head"><div><div class="kicker">GLOBAL NORTH–SOUTH</div><h2>North–South dashboard</h2><p class="muted dashboard-subtitle">This dashboard follows the selected year and skill level.</p></div><button id="closeSummary" class="iconbtn">×</button></div><div id="northSouthCurrent" class="summary-stats"></div><div id="northSouthNormalized" class="summary-stats normalized"></div><div class="cumulative-head"><div><h3>Cumulative since <span id="cumStart">—</span></h3><p class="small muted">Sum of built annual observations through <span id="cumEnd">—</span>.</p></div></div><div id="northSouthCumulative" class="summary-stats"></div><div class="charts-grid"><div class="chart-card wide"><div class="chart-head"><strong>Annual North–South labour flows</strong><span class="small muted">hours</span></div><svg id="nsFlowsChart" viewBox="0 0 900 280"></svg></div><div class="chart-card"><div class="chart-head"><strong>Annual net North appropriation</strong><span class="small muted">hours</span></div><svg id="nsNetChart" viewBox="0 0 700 260"></svg></div><div class="chart-card"><div class="chart-head"><strong>Annual wage value</strong><span class="small muted">constant 2005 EUR</span></div><svg id="nsValueChart" viewBox="0 0 700 260"></svg></div><div class="chart-card"><div class="chart-head"><strong>Cumulative net labour</strong><span class="small muted">hours</span></div><svg id="nsCumHoursChart" viewBox="0 0 700 260"></svg></div><div class="chart-card"><div class="chart-head"><strong>Cumulative wage value</strong><span class="small muted">constant 2005 EUR</span></div><svg id="nsCumValueChart" viewBox="0 0 700 260"></svg></div><div class="chart-card wide"><div class="chart-head"><strong id="countryTrendTitle">Selected-region trend</strong><span id="countryTrendMetric" class="small muted"></span></div><svg id="countryTrend" viewBox="0 0 900 260"></svg></div></div></section>
<section id="methodology" class="card section methodology"><div class="kicker">Methodology</div><h2>How the atlas works</h2><p class="method-intro">The atlas asks: <strong>where is the labour behind consumption performed?</strong> It then compares embodied labour in both directions.</p><div class="steps"><article class="step-card"><div class="step-number">1</div><div><h3>Follow production through the supply chain</h3><p>EXIOBASE links industries and products across countries, allowing labour to be traced through intermediate inputs as well as direct trade.</p></div></article><article class="step-card"><div class="step-number">2</div><div><h3>Count labour embodied in consumption</h3><p>Labour-hour data are attached to the production system and traced to each region's final demand.</p><div class="formula">H = q̂ (I − A)<sup>−1</sup> Y</div></div></article><article class="step-card"><div class="step-number">3</div><div><h3>Compare the two directions</h3><p>The atlas subtracts the reverse flow between each pair to show the net labour position.</p></div></article><article class="step-card"><div class="step-number">4</div><div><h3>Put the totals in context</h3><p>The same-year result is also shown per person, relative to domestic labour hours, and—on the wage-value view—as a share of GDP.</p><div class="formula">hours per person = net hours / population</div><div class="formula">wage value % GDP = net wage value / GDP × 100</div></div></article><article class="step-card"><div class="step-number">5</div><div><h3>Estimate the wage value</h3><p>The monetary view values net labour by skill using compensation per exported labour hour on the receiving side. It is a counterfactual, not an observed cash transfer.</p></div></article></div><div class="credits-block"><h3>Sources and methodological credit</h3><p>The supply-chain calculation is standard EEMRIO analysis. The unequal-exchange application follows Hickel, Hanbury Lemos and Barbour (2024).</p><p><strong>Hickel, J., Hanbury Lemos, M. & Barbour, F. (2024).</strong> <em>Unequal exchange of labour in the world economy.</em> Nature Communications 15, 6298. DOI: 10.1038/s41467-024-49687-y.</p><p><strong>Data:</strong> EXIOBASE 3.8.2. Annual population uses World Bank data with an open-data fallback for economies missing from that series.</p></div><div class="notice"><strong>Limitations:</strong> EXIOBASE uses now-casting for later years. Many Global South countries are contained within Rest-of-World regions. “Wage value as % of GDP” is a scale comparison; it does not mean that this share of GDP was literally transferred.</div></section>
<footer class="footer">Data: EXIOBASE 3.8.2. Unequal-exchange application adapted from Hickel, Hanbury Lemos & Barbour (2024).</footer></div>`;

const ids=["viewButtons","metric","skill","year","summaryBtn","methodologyBtn","playBtn","yearSlider","timelineYear","timelineRange","loading","details","legendScale","summaryPanel","closeSummary","northSouthCurrent","northSouthNormalized","northSouthCumulative","cumStart","cumEnd","nsFlowsChart","nsNetChart","nsValueChart","nsCumHoursChart","nsCumValueChart","countryTrend","countryTrendTitle","countryTrendMetric"],el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
let meta={},world=[],view="labour_hours",payload=null,selected=null,timer=null,cache=new Map();
const years=()=>[...(meta.years||[])].sort((a,b)=>a-b),nameOf=c=>meta.region_names?.[c]||c;
const compact=v=>d3.format(".3~s")(Math.abs(+v||0)).replace("G","B"),fmtHours=v=>`${v<0?"−":""}${compact(v)} h`,fmtEur=v=>`${v<0?"−":""}€${compact(v)}`,fmtPct=v=>Number.isFinite(+v)?`${(+v).toFixed(Math.abs(v)<10?1:0)}%`:"—",fmtPerson=v=>Number.isFinite(+v)?`${v<0?"−":""}${d3.format(",.1f")(Math.abs(v))}`:"—";
function metricOptions(){const opts=view==="labour_hours"?[["absolute","Net labour hours"],["per_capita","Hours per capita"],["relative","Net hours / domestic labour"]]:[["absolute","Net wage value"],["per_capita","Wage value per capita"],["relative","Wage value / GDP"]],prev=el.metric.value;el.metric.innerHTML=opts.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");el.metric.value=opts.some(x=>x[0]===prev)?prev:"absolute"}
function metricValue(d){if(el.metric.value==="absolute")return+d.net||0;if(el.metric.value==="per_capita")return+d.net_per_capita||0;return view==="labour_hours"?(+d.net_pct_domestic_labor||0):(+d.net_pct_gdp||0)}
function fmtMetric(v){if(el.metric.value==="absolute")return view==="labour_hours"?fmtHours(v):fmtEur(v);if(el.metric.value==="per_capita")return view==="labour_hours"?`${fmtPerson(v)} h/person`:`${v<0?"−":""}€${d3.format(",.0f")(Math.abs(+v||0))}/person`;return fmtPct(v)}
async function getPayload(v=view,skill=el.skill.value,year=+el.year.value){const k=`${v}-${skill}-${year}`;if(cache.has(k))return cache.get(k);const r=await fetch(dataUrl(`data/exio/${year}/${v}-${skill}.json`));if(!r.ok)throw new Error(`Derived EXIOBASE data for ${year} have not been built.`);const p=await r.json();cache.set(k,p);return p}
async function load(){try{payload=await getPayload();render();if(!el.summaryPanel.hidden)await renderNorthSouth()}catch(e){payload={regions:[],bilateral:[]};render();el.details.innerHTML=`<div class="notice">${e.message}</div>`}}
function rebuildYears(){const ys=years(),p=+el.year.value;el.year.innerHTML="";ys.slice().reverse().forEach(y=>el.year.add(new Option(y,y)));el.year.value=String(ys.includes(p)?p:ys.at(-1));syncSlider()}
function syncSlider(){const ys=years(),i=Math.max(0,ys.indexOf(+el.year.value));el.yearSlider.max=Math.max(0,ys.length-1);el.yearSlider.value=i;el.timelineYear.textContent=ys[i]??"—";el.timelineRange.textContent=ys.length?`${ys[0]} — ${ys.at(-1)}`:""}
function regionFor(d){return(meta.geometry||[]).find(x=>String(x.id)===String(d.id))?.exio_region||null}
function render(){if(!world.length||!payload)return;const by=new Map((payload.regions||[]).map(d=>[d.code,d])),vals=[...by.values()].map(metricValue),mx=d3.quantile(vals.map(Math.abs).sort(d3.ascending),.95)||1,color=d3.scaleLinear().domain([-mx,0,mx]).range(["#ef6a65","#596574","#59b7a8"]).clamp(true);el.legendScale.textContent=`${fmtMetric(-mx)} • 0 • ${fmtMetric(mx)}`;const svg=d3.select("#map"),proj=d3.geoNaturalEarth1().fitExtent([[15,15],[985,545]],{type:"Sphere"}),path=d3.geoPath(proj);svg.selectAll("path.country").data(world,d=>d.id).join("path").attr("class",d=>{const r=regionFor(d);return`country${r&&meta.row_regions.includes(r)?" aggregate":""}${selected===r?" selected":""}`}).attr("d",path).attr("fill",d=>{const r=by.get(regionFor(d));return r?color(metricValue(r)):"#1b2530"}).attr("opacity",d=>by.has(regionFor(d))?1:.42).on("click",(e,d)=>{const r=regionFor(d);if(r&&by.has(r)){selected=r;render();details(by.get(r));if(!el.summaryPanel.hidden)drawCountryTrend()}});svg.selectAll("path.sphere").data([{type:"Sphere"}]).join("path").attr("class","sphere").attr("d",path).attr("fill","none").attr("stroke","#354352");if(selected&&by.has(selected))details(by.get(selected));else el.details.innerHTML=`<div class="kicker">${view==="labour_hours"?"Labour appropriation":"Wage value"}</div><h2>${el.year.value}</h2><p class="muted">${SKILLS[el.skill.value]}</p><p class="muted">Select a country or aggregate.</p>`}
function details(d){const rel=(payload.bilateral||[]).filter(x=>x.from===d.code||x.to===d.code).sort((a,b)=>b.value-a.value).slice(0,12),absolute=view==="labour_hours"?fmtHours(d.net):fmtEur(d.net),percap=view==="labour_hours"?`${fmtPerson(d.net_per_capita)} h/person`:`${d.net_per_capita<0?"−":""}€${d3.format(",.0f")(Math.abs(+d.net_per_capita||0))}/person`,relative=view==="labour_hours"?fmtPct(d.net_pct_domestic_labor):fmtPct(d.net_pct_gdp),relativeLabel=view==="labour_hours"?"net hours / domestic labour":"wage value / GDP";el.details.innerHTML=`<div class="kicker">${d.aggregate?"EXIOBASE aggregate":"EXIOBASE country"} · ${d.code}</div><h2>${d.name}</h2>${d.aggregate?`<div class="aggregate-note">Regional aggregate, not a country-specific estimate. ${d.members?.length||0} mapped countries/territories.</div>`:""}<div class="muted">${el.year.value} · ${SKILLS[el.skill.value]}</div><div class="metric ${d.net>=0?"pos":"neg"}">${absolute}</div><div class="small muted">net ${view==="labour_hours"?"labour position":"wage-value position"}</div><div class="stats three"><div class="stat"><span class="small muted">Per capita</span><strong>${percap}</strong></div><div class="stat"><span class="small muted">${relativeLabel}</span><strong>${relative}</strong></div><div class="stat"><span class="small muted">Population</span><strong>${Number.isFinite(+d.population)?d3.format(".3~s")(d.population).replace("G","B"):"—"}</strong></div></div>${view==="labour_hours"?`<div class="stats"><div class="stat"><span class="small muted">Gross imported labour</span><strong>${fmtHours(d.gross_imported)}</strong></div><div class="stat"><span class="small muted">Gross exported labour</span><strong>${fmtHours(d.gross_exported)}</strong></div></div>`:`<div class="stat standalone"><span class="small muted">EXIOBASE GDP</span><strong>${fmtEur(d.gdp_eur_2005)}</strong></div>`}<div class="flows"><strong>Largest net bilateral relationships</strong>${rel.map(f=>`<div class="flow"><span>${f.to===d.code?"← "+nameOf(f.from):"→ "+nameOf(f.to)}</span><span>${view==="labour_hours"?fmtHours(f.value):fmtEur(f.value)}</span></div>`).join("")||'<p class="muted">No net bilateral relationships.</p>'}</div>${d.aggregate?`<details class="members"><summary>Countries contained in this aggregate</summary><p>${(d.members||[]).join(", ")}</p></details>`:""}`}
function nsFor(year,skill=el.skill.value){return meta.north_south_by_year?.[String(year)]?.by_selection?.[skill]||null}
function nsSeries(){return years().map(year=>({year,d:nsFor(year)})).filter(x=>x.d)}
const card=([label,value,note])=>`<div class="summary-stat"><span class="small muted">${label}</span><strong>${value}</strong><span class="small muted">${note}</span></div>`;
async function renderNorthSouth(){const current=nsFor(+el.year.value);if(!current){el.northSouthCurrent.innerHTML='<div class="notice">North–South data are not available for this year.</div>';return}el.northSouthCurrent.innerHTML=[["South → North labour",fmtHours(current.south_to_north_hours),"gross embodied hours"],["North → South labour",fmtHours(current.north_to_south_hours),"gross embodied hours"],["Net North appropriation",fmtHours(current.net_north_appropriation_hours),"South → North minus reverse flow"],["Northern-wage value",fmtEur(current.wage_value_2005_eur),"counterfactual wage value"]].map(card).join("");el.northSouthNormalized.innerHTML=[["North: net hours/person",`${fmtPerson(current.north_net_hours_per_capita)} h/person`,"selected year"],["South: net hours/person",`${fmtPerson(current.south_net_hours_per_capita)} h/person`,"negative = net supply"],["Value / North GDP",fmtPct(current.wage_value_pct_north_gdp),"equivalent share of GDP"],["Value / South GDP",fmtPct(current.wage_value_pct_south_gdp),"equivalent share of GDP"]].map(card).join("");const selectedYear=+el.year.value,series=nsSeries().filter(x=>x.year<=selectedYear);let cumSTN=0,cumNTS=0,cumNet=0,cumValue=0;const cumulative=series.map(x=>{cumSTN+=x.d.south_to_north_hours;cumNTS+=x.d.north_to_south_hours;cumNet+=x.d.net_north_appropriation_hours;cumValue+=x.d.wage_value_2005_eur;return{year:x.year,stn:cumSTN,nts:cumNTS,net:cumNet,value:cumValue}});el.cumStart.textContent=cumulative[0]?.year??"—";el.cumEnd.textContent=selectedYear;el.northSouthCumulative.innerHTML=[["Cumulative South → North",fmtHours(cumSTN),"sum of annual gross flows"],["Cumulative North → South",fmtHours(cumNTS),"sum of annual gross flows"],["Cumulative net labour",fmtHours(cumNet),"net North appropriation"],["Cumulative wage value",fmtEur(cumValue),"constant 2005 EUR"]].map(card).join("");drawTwoLine(el.nsFlowsChart,series.map(x=>({year:x.year,a:x.d.south_to_north_hours,b:x.d.north_to_south_hours})),"South → North","North → South","hours");drawOneLine(el.nsNetChart,series.map(x=>({year:x.year,value:x.d.net_north_appropriation_hours})),"hours");drawOneLine(el.nsValueChart,series.map(x=>({year:x.year,value:x.d.wage_value_2005_eur})),"eur");drawOneLine(el.nsCumHoursChart,cumulative.map(x=>({year:x.year,value:x.net})),"hours");drawOneLine(el.nsCumValueChart,cumulative.map(x=>({year:x.year,value:x.value})),"eur");await drawCountryTrend()}
const clear=n=>d3.select(n).selectAll("*").remove();
function axes(svg,data,W,H,m,unit){const x=d3.scalePoint().domain(data.map(d=>d.year)).range([m.l,W-m.r]).padding(.25),values=data.flatMap(d=>["value","a","b"].map(k=>d[k]).filter(Number.isFinite));let[lo,hi]=d3.extent(values);lo=Math.min(lo??0,0);hi=Math.max(hi??1,0);if(lo===hi)hi=lo+1;const y=d3.scaleLinear().domain([lo,hi]).nice().range([H-m.b,m.t]),step=Math.max(1,Math.ceil(data.length/8));svg.append("g").attr("transform",`translate(0,${H-m.b})`).call(d3.axisBottom(x).tickValues(data.filter((_,i)=>i%step===0).map(d=>d.year))).call(g=>g.selectAll("text").attr("fill","#9aa8b6")).call(g=>g.selectAll("line,path").attr("stroke","#354352"));svg.append("g").attr("transform",`translate(${m.l},0)`).call(d3.axisLeft(y).ticks(5).tickFormat(v=>unit==="eur"?"€"+d3.format(".2s")(v).replace("G","B"):d3.format(".2s")(v))).call(g=>g.selectAll("text").attr("fill","#9aa8b6")).call(g=>g.selectAll("line,path").attr("stroke","#354352"));return{x,y}}
function drawOneLine(node,data,unit){clear(node);if(!data.length)return;const svg=d3.select(node),vb=node.viewBox.baseVal,W=vb.width||700,H=vb.height||260,m={t:20,r:22,b:34,l:90},{x,y}=axes(svg,data,W,H,m,unit);svg.append("path").datum(data).attr("fill","none").attr("stroke","#e0b85a").attr("stroke-width",2.5).attr("d",d3.line().x(d=>x(d.year)).y(d=>y(d.value)))}
function drawTwoLine(node,data,labelA,labelB,unit){clear(node);if(!data.length)return;const svg=d3.select(node),vb=node.viewBox.baseVal,W=vb.width||900,H=vb.height||280,m={t:32,r:22,b:34,l:90},{x,y}=axes(svg,data,W,H,m,unit),lines=[["a",labelA,"#59b7a8"],["b",labelB,"#ef6a65"]];for(const[k,label,color]of lines)svg.append("path").datum(data).attr("fill","none").attr("stroke",color).attr("stroke-width",2.4).attr("d",d3.line().x(d=>x(d.year)).y(d=>y(d[k])));const legend=svg.append("g").attr("transform",`translate(${m.l},12)`);lines.forEach(([k,label,color],i)=>{const g=legend.append("g").attr("transform",`translate(${i*180},0)`);g.append("line").attr("x1",0).attr("x2",22).attr("stroke",color).attr("stroke-width",3);g.append("text").attr("x",28).attr("y",4).attr("fill","#cdd6df").attr("font-size",12).text(label)})}
async function drawCountryTrend(){clear(el.countryTrend);if(!selected){d3.select(el.countryTrend).append("text").attr("x",20).attr("y",40).attr("fill","#9aa8b6").text("Select a region on the map to show its history.");return}const s=[];for(const y of years()){try{const p=await getPayload(view,el.skill.value,y),r=(p.regions||[]).find(d=>d.code===selected);if(r)s.push({year:y,value:metricValue(r)})}catch{}}el.countryTrendTitle.textContent=`${nameOf(selected)} over time`;el.countryTrendMetric.textContent=el.metric.options[el.metric.selectedIndex]?.text||"";drawOneLine(el.countryTrend,s,(view==="wage_value"&&el.metric.value==="absolute")?"eur":"raw")}
function stop(){if(timer)clearInterval(timer);timer=null;el.playBtn.textContent="▶"}
el.playBtn.addEventListener("click",()=>{if(timer){stop();return}const ys=years();if(ys.length<2)return;timer=setInterval(()=>{let i=+el.yearSlider.value+1;if(i>=ys.length)i=0;el.yearSlider.value=i;el.year.value=ys[i];el.timelineYear.textContent=ys[i];load()},1100);el.playBtn.textContent="❚❚"});
el.yearSlider.addEventListener("input",()=>{const y=years()[+el.yearSlider.value];if(y!=null){el.year.value=y;el.timelineYear.textContent=y;load()}});
el.year.addEventListener("change",()=>{syncSlider();load()});el.skill.addEventListener("change",load);el.metric.addEventListener("change",()=>{render();if(!el.summaryPanel.hidden)drawCountryTrend()});el.viewButtons.addEventListener("click",e=>{const b=e.target.closest("button[data-view]");if(!b)return;view=b.dataset.view;[...el.viewButtons.children].forEach(x=>x.classList.toggle("active",x===b));metricOptions();load()});el.summaryBtn.addEventListener("click",async()=>{el.summaryPanel.hidden=false;await renderNorthSouth();el.summaryPanel.scrollIntoView({behavior:"smooth"})});el.closeSummary.addEventListener("click",()=>el.summaryPanel.hidden=true);el.methodologyBtn.addEventListener("click",()=>document.querySelector("#methodology").scrollIntoView({behavior:"smooth"}));
async function init(){try{const[topo,m]=await Promise.all([fetch("https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json").then(r=>r.ok?r.json():Promise.reject(new Error("Map geometry failed"))),fetch(dataUrl("data/exio/meta.json")).then(r=>r.ok?r.json():Promise.reject(new Error("EXIOBASE metadata missing")))]);meta=m;world=feature(topo,topo.objects.countries).features;if(!meta.years?.length)throw new Error("No EXIOBASE years have been built yet. Run the data workflow.");metricOptions();rebuildYears();el.loading.remove();await load()}catch(e){el.loading.innerHTML=`<strong>Data build required.</strong><br>${e.message}`;el.details.innerHTML="<div class='muted'>Run the EXIOBASE workflow first.</div>"}}
init();